// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8qYVWVWBdkWkU7a7Lw2BHE9tXumDqRcc',
    appId: '1:523713928025:web:4c7195a7a4305fbbd80a48',
    messagingSenderId: '523713928025',
    projectId: 'flutter-map-e1df2',
    authDomain: 'flutter-map-e1df2.firebaseapp.com',
    storageBucket: 'flutter-map-e1df2.appspot.com',
    measurementId: 'G-N5HZ9BRW1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtzBh0aEytgTxOg2CywhoVk7FrJ5cMSj0',
    appId: '1:523713928025:android:68973af473caa8a7d80a48',
    messagingSenderId: '523713928025',
    projectId: 'flutter-map-e1df2',
    storageBucket: 'flutter-map-e1df2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtpQ08BEzF3nkkFDdD4_zn9QPy3g0v-IE',
    appId: '1:523713928025:ios:088e7dc7235fbbc3d80a48',
    messagingSenderId: '523713928025',
    projectId: 'flutter-map-e1df2',
    storageBucket: 'flutter-map-e1df2.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtpQ08BEzF3nkkFDdD4_zn9QPy3g0v-IE',
    appId: '1:523713928025:ios:2f54a4110b7c27e5d80a48',
    messagingSenderId: '523713928025',
    projectId: 'flutter-map-e1df2',
    storageBucket: 'flutter-map-e1df2.appspot.com',
    iosBundleId: 'com.example.todoList.RunnerTests',
  );
}
